function [ term ] = f_int_mind_dx_q(u,v,w,x,y,z,ni )

%Eq(5) of Vaziri et al.

script_int_mind

term=(3-4.*ni).*(Y.*log(X+R1)+X.*log(Y+R1)...
    +2.*Z1.*Tz1+Y.*log(X+R2)+2.*Z2.*Tz2)...
    +Y.*log(X+R2)+X.*log(Y+R2)...
    +2.*Z2.*Tz2+Y.*log(X+R1)+2.*Z1.*Tz1...
    +(2.*w.*z.*X.*Y)./(R2.*(X.^2+Z2.^2))+4.*(1-ni).*(1-2.*ni)...
    .*(X.*log(Y+R2)-2.*Z2.*Tx2);
end

